version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.6
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - checkout

      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}

      - run:
          name: Vendoring
          command: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Run Tests
          command: go test -v local.packages/...
