version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.6
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    commands:
      go_mod_download:
        steps:
          - restore_cache:
              name: Restore go modules cache
              keys:
                - go-modules-{{ checksum "go.sum" }}

          - run: go mod download

          - save_cache:
              name: Save go modules cache
              key: go-modules-{{ checksum "go.sum" }}
              paths:
                - "/go/pkg/mod"
    steps:
      - checkout
      - go_mod_download

      - run:
          name: Run Tests
          command: go test -v local.packages/...
